//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark Function Pointers and Blocks

typedef void (*CDUnknownFunctionPointerType)(void); // return type and parameters are unknown

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct t_etm_bt_file {
    unsigned int _field1;
    _Bool _field2;
    int _field3;
    unsigned long long _field4;
    unsigned long long _field5;
    unsigned int _field6;
};

struct t_etm_create_task {
    int _field1;
    char *_field2;
    unsigned int _field3;
    char *_field4;
    unsigned int _field5;
    char *_field6;
    unsigned int _field7;
    char *_field8;
    unsigned int _field9;
    char *_field10;
    unsigned int _field11;
    unsigned int *_field12;
    unsigned int _field13;
    char *_field14;
    unsigned long long _field15;
    char *_field16;
    void *_field17;
    unsigned int _field18;
    int _field19;
};

struct t_etm_hsc_info {
    int _state;
    int _file_index;
    unsigned long long _dl_bytes;
    unsigned int _speed;
    int _errcode;
};

struct t_etm_task_info {
    unsigned int _task_id;
    int _state;
    int _type;
    char _file_name[512];
    char _file_path[512];
    unsigned long long _file_size;
    unsigned long long _downloaded_data_size;
    unsigned int _all_download_speed;
    unsigned int _errcode;
    unsigned int _start_time;
    unsigned int _finished_time;
    unsigned int _failed_code;
    unsigned int _bt_total_file_num;
    _Bool _is_deleted;
    _Bool _is_url_play;
    unsigned int sub_task_count;
    unsigned int task_flag;
};

struct t_etm_torrent_file_info {
    unsigned int _field1;
    char *_field2;
    unsigned int _field3;
    char *_field4;
    unsigned int _field5;
    unsigned long long _field6;
    unsigned long long _field7;
};

struct t_etm_torrent_seed_info {
    char _field1[504];
    unsigned int _field2;
    unsigned long long _field3;
    unsigned int _field4;
    unsigned int _field5;
    unsigned char _field6[20];
    struct t_etm_torrent_file_info *_field7;
};

struct tagETM_MAGNET_INFO {
    char _field1[512];
    unsigned long long _field2;
    unsigned char _field3[20];
};

struct tagXLStatParam {
    char *_field1;
    char *_field2;
    char *_field3;
    char *_field4;
    char *_field5;
    char *_field6;
    char *_field7;
    char *_field8;
    char *_field9;
    char *_field10;
    char *_field11;
    unsigned int _field12;
    unsigned int _field13;
    unsigned int _field14;
    char *_field15;
    char *_field16;
    char *_field17;
    char *_field18;
    unsigned int _field19;
    unsigned int _field20;
    char *_field21;
    unsigned long long _field22;
    _Bool _field23;
};

struct vip_accelerate_info {
    unsigned int _field1;
    unsigned long long _field2;
    unsigned int _field3;
    int _field4;
};

