//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface EtmApi : NSObject
{
    BOOL isInitSucc;
}

+ (id)sharedInstance;
- (BOOL)stat_track_event:(unsigned long long)arg1 event:(const char *)arg2 attr1:(const char *)arg3 attr2:(const char *)arg4 cost1:(unsigned int)arg5 cost2:(unsigned int)arg6 cost3:(unsigned int)arg7 cost4:(unsigned int)arg8 ext_data:(const char *)arg9;
- (void)stat_uninit:(unsigned long long)arg1;
- (BOOL)stat_init:(struct tagXLStatParam *)arg1 key:(unsigned long long *)arg2;
- (void)stat_prepare_param:(struct tagXLStatParam *)arg1;
- (void)stat_realtime_report:(unsigned long long)arg1;
- (void)stat_set_current_net_type:(unsigned long long)arg1 netType:(unsigned int)arg2;
- (int)etm_set_task_flag:(unsigned int)arg1 flag:(unsigned int)arg2;
- (void)etm_get_filesize_from_url:(id)arg1 callback:(CDUnknownFunctionPointerType)arg2;
- (const char *)etm_get_task_play_url:(unsigned int)arg1 subTask:(unsigned int)arg2;
- (id)etm_version;
- (id)parserThunderURL:(id)arg1;
- (const char *)etm_get_bt_magnet_url:(unsigned int)arg1;
- (int)etm_parse_magnet:(char *)arg1 info:(struct tagETM_MAGNET_INFO *)arg2;
- (id)gcidWithTask:(unsigned long long)arg1;
- (id)cidWithTask:(unsigned long long)arg1;
- (BOOL)setTaskStateChangedCallBack:(CDUnknownFunctionPointerType)arg1;
- (int)etm_set_user_info:(unsigned long long)arg1 jumpKey:(id)arg2 sessionId:(id)arg3 vipLevel:(unsigned short)arg4 vipType:(unsigned char)arg5;
- (int)etm_stop_vip_accelerate:(unsigned int)arg1;
- (int)etm_start_vip_channel_accelerate:(unsigned int)arg1;
- (int)etm_get_vip_info:(unsigned int)arg1 hscInfo:(struct t_etm_hsc_info *)arg2;
- (int)etm_restart_try_vip_channel_accelerate:(unsigned int)arg1;
- (int)etm_try_vip_channel_accelerate:(unsigned int)arg1;
- (BOOL)etm_is_vip_channel_can_try:(unsigned int)arg1;
- (int)etm_try_accelerate_timeup:(unsigned int)arg1;
- (BOOL)getTaskInfo:(unsigned long long)arg1 pEtmTaskInfo:(struct t_etm_task_info *)arg2;
- (id)allTaskids;
- (const char *)etm_get_bt_task_seed_file:(unsigned int)arg1;
- (int)etm_get_bt_file_info:(unsigned int)arg1 fileIndex:(unsigned int)arg2 btFileInfo:(struct t_etm_bt_file *)arg3;
- (int)etm_set_bt_need_download_file_index:(unsigned int)arg1 newFileIndexArray:(unsigned int *)arg2 newFileNum:(unsigned int)arg3;
- (int)etm_get_bt_need_download_file_index:(unsigned int)arg1 idArrayBuffer:(unsigned int *)arg2 bufferLen:(unsigned int *)arg3;
- (int)etm_release_torrent_seed_info:(struct t_etm_torrent_seed_info *)arg1;
- (int)etm_get_torrent_seed_info:(char *)arg1 encoding:(int)arg2 seedInfo:(struct t_etm_torrent_seed_info **)arg3;
- (const char *)etm_get_task_ref_url:(unsigned int)arg1;
- (const char *)etm_get_task_url:(unsigned int)arg1;
- (int)etm_set_max_tasks:(unsigned int)arg1;
- (int)etm_set_upload_limit_speed:(unsigned int)arg1;
- (int)etm_set_download_limit_speed:(unsigned int)arg1;
- (int)etm_get_task_info:(unsigned int)arg1 pTaskInfo:(struct t_etm_task_info *)arg2;
- (int)etm_recover_task:(unsigned int)arg1;
- (int)etm_destroy_task:(unsigned int)arg1 removeFileFlag:(BOOL)arg2;
- (int)etm_delete_task:(unsigned int)arg1;
- (int)etm_pause_task:(unsigned int)arg1;
- (int)etm_resume_task:(unsigned int)arg1;
- (int)etm_rename_task:(unsigned int)arg1 newName:(const char *)arg2 newNameLen:(unsigned int)arg3;
- (int)etm_set_file_name_changed_callback:(CDUnknownFunctionPointerType)arg1;
- (int)etm_get_all_task_ids:(unsigned int *)arg1 pBufferLen:(unsigned int *)arg2;
- (int)etm_create_task:(struct t_etm_create_task *)arg1 pTaskId:(unsigned int *)arg2;
- (int)etm_set_download_path:(const char *)arg1 pathLen:(unsigned int)arg2;
- (id)init;
- (int)etm_uninit;
- (void)run;

@end

